### PR TITLE
Removed NSLogs

### PR DESCRIPTION
**Pull request by Przytua**
**WARNING** https://github.com/ApplauseAQI/ASScreenRecorder/pull/4 must be merged before this one
- got rid of NSLogs
- Added delegate methods to inform about errors
- Moved method for custom drawing from delegate to datasource

### CODE REVIEW

**Comment by azubala** [comment]
Please rebase.

**Comment by azubala** [comment]
I would love to refactor this class a bit, but let's postpone it until we roll out 3.0.0 of the SDK.

**Comment by Przytua** [comment]
Do you mean splitting it into multiple classes?

**Comment by azubala** [comment]
I mean general refactor, we could definitely improve the quality of the code style.  

## 

Aleksander Zubala

**Pull request merged**
